### ISSUE TITLE
Support recursive relationships

### ISSUE THREAD

**Issue by tkamenoko** [mswjs/data#132]
`@msw/data` does not support recursive relationships, but it is useful for mocking social media like Twitter, Facebook, etc. 

Test code:

```ts
import { factory, manyOf, primaryKey } from '@msw/data'
import { v4 } from 'uuid'

test('supports recursive relationships', () => {
  const db = factory({
    user: {
      id: primaryKey(v4),
      friends: manyOf('user'),
    },
  })
  const firstUser = db.user.create({ friends: [] })
  const secondUser = db.user.create({ friends: [firstUser] })
  db.user.update({
    where: { id: { equals: firstUser.id } },
    data: { friends: [secondUser] },
  })
  expect(secondUser.friends[0].id).toEqual(firstUser.id)
})
```

Current output:
```
RangeError: Maximum call stack size exceeded
        at JSON.stringify (<anonymous>)

      55 | function executeQuery(modelName, primaryKey, query, db) {
      56 |     var _a;
    > 57 |     log(JSON.stringify(query) + " on \"" + modelName + "\"");
         |              ^
      58 |     log('using primary key "%s"', primaryKey);
      59 |     var records = db.getModel(modelName);
      60 |     // Reduce the query scope if there's a query by primary key of the model.

      at Object.executeQuery (lib/query/executeQuery.js:57:14)
      at lib/relations/Relation.js:137:57
          at Array.reduce (<anonymous>)
      at Object.get [as friends] (lib/relations/Relation.js:135:50)
          at Function.entries (<anonymous>)
      at removeInternalProperties (lib/utils/removeInternalProperties.js:51:39)
      at lib/utils/removeInternalProperties.js:72:32
          at Array.map (<anonymous>)
      at removeInternalProperties (lib/utils/removeInternalProperties.js:70:50)
      at lib/utils/removeInternalProperties.js:72:32
          at Array.map (<anonymous>)
      // same output continues...
      at removeInternalProperties (lib/utils/removeInternalProperties.js:70:50)
      at lib/utils/removeInternalProperties.js:72:32
          at Array.map (<anonymous>)
```

**Comment by kettanaito** [comment]
Hey, @tkamenoko. Thank you for suggesting this!

I think this library can benefit from supporting recursive relationships. I particularly like your example for its simplicity. 

So the infinite cycle is triggered by the `removeInternalProperties` function that's designed to return developer-friendly data stripped of all internal properties like `__type` and `__primaryKey`. When cleaning `firstUser` it eventually encounters `firstUser.friends` and understand that it's a relation:

https://github.com/mswjs/data/blob/35077afb48e4bbbfdb353c764f6fcf255138578b/src/utils/removeInternalProperties.ts#L62-L67

So it iterates over all referenced entities and removes internal properties from them as well. What goes wrong is that one of the referenced entities has its own `.friends` property which now references `firstUser` (we are still in the `.map` recursive call right now), and thus the infinity spawns.
